### ISSUE TITLE
Изменение размера изображения

### ISSUE THREAD

**Issue by Alolag** [TigerMehMat/pic#1]
Непонятно, какой тип интерполяции используется в stretch.

Каким именно методом изменяется размер изображения в stretch? Методом ближайшего соседа? Билинейной или бикубической интерполяцией? Или что-то другое? А если нужно что-то особенное?

**Comment by TigerMehMat** [comment]
Функция использует [imagecopyresized](http://php.net/manual/en/function.imagecopyresized.php), стандартный в PHP.
